# utils/comparison_exporter.py
# Exports paper comparison to formatted DOCX and PDF.
# Colour-coded score table + full narrative sections.

import os
import io
from datetime import datetime
from utils.comparison_chain import DIMENSION_LABELS


# ── DOCX Export ───────────────────────────────────────────────────────────────
def export_comparison_to_docx(comparison_data: dict) -> bytes:
    """
    Exports the full comparison to a Word document.
    Includes:
    - Cover page with papers and winner
    - Colour-coded score table
    - Narrative section per dimension
    Returns bytes for Streamlit download.
    """
    from docx import Document
    from docx.shared import Pt, Inches, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement

    doc     = Document()
    papers  = comparison_data["papers"]
    scores  = comparison_data["scores"]
    totals  = comparison_data["totals"]
    winner  = comparison_data["winner"]
    winner_idx = comparison_data["winner_index"]

    # ── Page margins ──────────────────────────────────────────
    section = doc.sections[0]
    section.top_margin    = Inches(1)
    section.bottom_margin = Inches(1)
    section.left_margin   = Inches(1.2)
    section.right_margin  = Inches(1.2)

    # ── Color constants ───────────────────────────────────────
    BLUE   = RGBColor(0x1F, 0x77, 0xB4)
    GREEN  = RGBColor(0x28, 0xA7, 0x45)
    GOLD   = RGBColor(0xFF, 0xC1, 0x07)
    LIGHT  = RGBColor(0xEB, 0xF5, 0xFB)
    WHITE  = RGBColor(0xFF, 0xFF, 0xFF)
    DARK   = RGBColor(0x1A, 0x1A, 0x1A)
    GRAY   = RGBColor(0x66, 0x66, 0x66)

    def _shd(cell, hex_color: str):
        """Apply background color to a table cell."""
        tc   = cell._tc
        tcPr = tc.get_or_add_tcPr()
        shd  = OxmlElement("w:shd")
        shd.set(qn("w:val"),   "clear")
        shd.set(qn("w:color"), "auto")
        shd.set(qn("w:fill"),  hex_color)
        tcPr.append(shd)

    def _score_color(score: int) -> str:
        """Returns hex color based on score value."""
        if score >= 8:
            return "D4EDDA"   # green tint
        elif score >= 6:
            return "FFF3CD"   # amber tint
        else:
            return "F8D7DA"   # red tint

    def add_heading(text: str, level: int = 1):
        h   = doc.add_heading(text, level=level)
        h.alignment = WD_ALIGN_PARAGRAPH.LEFT
        run = h.runs[0] if h.runs else h.add_run()
        run.font.color.rgb = BLUE
        run.font.name      = "Calibri"
        return h

    def add_body(text: str):
        p = doc.add_paragraph(text)
        p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        for run in p.runs:
            run.font.size = Pt(11)
            run.font.name = "Calibri"
        return p

    def add_divider():
        para = doc.add_paragraph()
        pPr  = para._p.get_or_add_pPr()
        pBdr = OxmlElement("w:pBdr")
        bot  = OxmlElement("w:bottom")
        bot.set(qn("w:val"),   "single")
        bot.set(qn("w:sz"),    "6")
        bot.set(qn("w:space"), "1")
        bot.set(qn("w:color"), "1F77B4")
        pBdr.append(bot)
        pPr.append(pBdr)

    # ── Cover page ────────────────────────────────────────────
    doc.add_paragraph()
    t = doc.add_paragraph()
    t.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = t.add_run("Paper Comparison Report")
    r.font.size      = Pt(26)
    r.font.bold      = True
    r.font.color.rgb = BLUE
    r.font.name      = "Calibri"

    doc.add_paragraph()
    d = doc.add_paragraph()
    d.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = d.add_run(
        f"Comparing {len(papers)} Research Papers\n"
        f"Generated: {datetime.now().strftime('%B %d, %Y')}\n"
        f"Generated by RAG Research Assistant"
    )
    r.font.size      = Pt(11)
    r.font.color.rgb = GRAY
    r.font.name      = "Calibri"

    doc.add_paragraph()

    # Winner announcement
    w_para = doc.add_paragraph()
    w_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    w_run  = w_para.add_run(f"🏆 Overall Winner: {winner}")
    w_run.font.size      = Pt(13)
    w_run.font.bold      = True
    w_run.font.color.rgb = GREEN
    w_run.font.name      = "Calibri"

    if comparison_data.get("winner_reason"):
        wr = doc.add_paragraph()
        wr.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r  = wr.add_run(comparison_data["winner_reason"])
        r.font.size      = Pt(10)
        r.font.color.rgb = GRAY
        r.font.name      = "Calibri"
        r.font.italic    = True

    doc.add_page_break()

    # ── Papers list ───────────────────────────────────────────
    add_heading("Papers Compared", level=1)
    for i, paper in enumerate(papers):
        meta   = comparison_data["metadata"][i]
        authors = meta.get("authors", ["Unknown"])
        author_str = (
            f"{authors[0]} et al." if len(authors) > 2
            else ", ".join(authors)
        )
        p   = doc.add_paragraph(style="List Number")
        run = p.add_run(
            f"{paper} ({author_str}, {meta.get('year', 'n.d.')})"
        )
        run.font.size = Pt(10)
        run.font.name = "Calibri"
        if i == winner_idx:
            run.font.bold      = True
            run.font.color.rgb = GREEN

    add_divider()
    doc.add_paragraph()

    # ── Part A: Score table ───────────────────────────────────
    add_heading("Part A — Comparative Scores", level=1)
    add_body(
        "The following table scores each paper (1–10) across six key "
        "dimensions. Green = strong (8–10), Amber = moderate (6–7), "
        "Red = weak (1–5). The paper with the highest total is the winner."
    )
    doc.add_paragraph()

    dims_to_score = [d for d in DIMENSION_LABELS if d != "overall"]
    n_cols = 1 + len(papers) + 1  # Dimension + papers + Max

    table = doc.add_table(
        rows=1 + len(dims_to_score) + 1,
        cols=n_cols
    )
    table.style = "Table Grid"

    # Header row
    headers = ["Dimension"] + [
        p[:25] + "..." if len(p) > 25 else p
        for p in papers
    ] + ["Max"]

    hdr = table.rows[0]
    for ci, htext in enumerate(headers):
        cell = hdr.cells[ci]
        cell.text = htext
        run  = cell.paragraphs[0].runs[0]
        run.font.bold      = True
        run.font.size      = Pt(9)
        run.font.name      = "Calibri"
        run.font.color.rgb = WHITE
        _shd(cell, "1F77B4")

    # Score rows
    for ri, dim in enumerate(dims_to_score):
        row    = table.rows[ri + 1]
        label  = DIMENSION_LABELS[dim]
        dim_sc = scores.get(dim, [5] * len(papers))

        # Dimension label cell
        row.cells[0].text = label
        r = row.cells[0].paragraphs[0].runs[0]
        r.font.size = Pt(9)
        r.font.name = "Calibri"
        r.font.bold = True

        # Score cells
        for ci, sc in enumerate(dim_sc):
            cell      = row.cells[ci + 1]
            cell.text = str(sc)
            run       = cell.paragraphs[0].runs[0]
            run.font.size = Pt(10)
            run.font.bold = True
            run.font.name = "Calibri"
            _shd(cell, _score_color(sc))
            # Centre align
            cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Max score cell
        max_sc = max(dim_sc)
        row.cells[-1].text = str(max_sc)
        r = row.cells[-1].paragraphs[0].runs[0]
        r.font.size = Pt(9)
        r.font.name = "Calibri"
        _shd(row.cells[-1], "E8F4FD")

    # Totals row
    tot_row = table.rows[-1]
    tot_row.cells[0].text = "TOTAL"
    r = tot_row.cells[0].paragraphs[0].runs[0]
    r.font.bold = True
    r.font.size = Pt(9)
    r.font.name = "Calibri"
    _shd(tot_row.cells[0], "1F77B4")
    r.font.color.rgb = WHITE

    for ci, total in enumerate(totals):
        cell = tot_row.cells[ci + 1]
        cell.text = str(total)
        run = cell.paragraphs[0].runs[0]
        run.font.bold = True
        run.font.size = Pt(10)
        run.font.name = "Calibri"
        cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
        if ci == winner_idx:
            _shd(cell, "28A745")
            run.font.color.rgb = WHITE
        else:
            _shd(cell, "D4EDDA")

    # Max total cell
    tot_row.cells[-1].text = str(max(totals))
    r = tot_row.cells[-1].paragraphs[0].runs[0]
    r.font.size = Pt(9)
    r.font.name = "Calibri"
    _shd(tot_row.cells[-1], "1F77B4")
    r.font.color.rgb = WHITE

    doc.add_paragraph()
    winner_para = doc.add_paragraph()
    wr = winner_para.add_run(
        f"🏆 Winner: {winner}  |  Score: {totals[winner_idx]}/{len(dims_to_score)*10}"
    )
    wr.font.bold      = True
    wr.font.size      = Pt(11)
    wr.font.color.rgb = GREEN
    wr.font.name      = "Calibri"

    doc.add_page_break()

    # ── Part B: Narrative sections ────────────────────────────
    add_heading("Part B — Detailed Narrative Analysis", level=1)
    add_body(
        "The following sections provide a deep analytical comparison "
        "of each dimension, examining agreements, contradictions, "
        "and relative strengths across all papers."
    )
    doc.add_paragraph()

    narratives = comparison_data.get("narratives", {})
    for i, (dim, label) in enumerate(DIMENSION_LABELS.items(), 1):
        add_heading(f"{i}. {label}", level=2)
        text = narratives.get(dim, "Analysis not available.")
        for para in text.split("\n\n"):
            if para.strip():
                add_body(para.strip())
        doc.add_paragraph()

    # ── Save to bytes ─────────────────────────────────────────
    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.getvalue()


# ── PDF Export ────────────────────────────────────────────────────────────────
def export_comparison_to_pdf(comparison_data: dict) -> bytes:
    """
    Exports the comparison to a formatted PDF.
    Returns bytes for Streamlit download.
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer,
        Table, TableStyle, PageBreak, HRFlowable
    )
    from reportlab.lib.enums import TA_JUSTIFY, TA_CENTER, TA_LEFT

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        rightMargin=1.2*inch, leftMargin=1.2*inch,
        topMargin=1.0*inch,  bottomMargin=1.0*inch
    )

    BLUE  = colors.HexColor("#1F77B4")
    GREEN = colors.HexColor("#28A745")
    GOLD  = colors.HexColor("#FFC107")
    GRAY  = colors.HexColor("#666666")
    LIGHT = colors.HexColor("#EBF5FB")

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "CTitle", parent=styles["Title"],
        fontSize=24, textColor=BLUE,
        spaceAfter=12, alignment=TA_CENTER,
        fontName="Helvetica-Bold"
    )
    heading1 = ParagraphStyle(
        "CH1", parent=styles["Heading1"],
        fontSize=14, textColor=BLUE,
        spaceBefore=16, spaceAfter=8,
        fontName="Helvetica-Bold"
    )
    heading2 = ParagraphStyle(
        "CH2", parent=styles["Heading2"],
        fontSize=12, textColor=BLUE,
        spaceBefore=12, spaceAfter=6,
        fontName="Helvetica-Bold"
    )
    body_style = ParagraphStyle(
        "CBody", parent=styles["Normal"],
        fontSize=10, leading=16,
        spaceAfter=8, alignment=TA_JUSTIFY,
        fontName="Helvetica"
    )
    winner_style = ParagraphStyle(
        "CWin", parent=styles["Normal"],
        fontSize=12, textColor=GREEN,
        alignment=TA_CENTER, fontName="Helvetica-Bold",
        spaceAfter=6
    )

    papers     = comparison_data["papers"]
    scores     = comparison_data["scores"]
    totals     = comparison_data["totals"]
    winner     = comparison_data["winner"]
    winner_idx = comparison_data["winner_index"]
    narratives = comparison_data.get("narratives", {})

    story = []

    # ── Cover ─────────────────────────────────────────────────
    story.append(Spacer(1, 1*inch))
    story.append(Paragraph("Paper Comparison Report", title_style))
    story.append(Spacer(1, 0.2*inch))
    story.append(Paragraph(
        f"Comparing {len(papers)} Research Papers  ·  "
        f"{datetime.now().strftime('%B %d, %Y')}",
        ParagraphStyle("meta", parent=styles["Normal"],
                       fontSize=10, textColor=GRAY,
                       alignment=TA_CENTER)
    ))
    story.append(Spacer(1, 0.3*inch))
    story.append(Paragraph(f"Overall Winner: {winner}", winner_style))

    if comparison_data.get("winner_reason"):
        story.append(Paragraph(
            comparison_data["winner_reason"],
            ParagraphStyle("wr", parent=styles["Normal"],
                           fontSize=9, textColor=GRAY,
                           alignment=TA_CENTER, fontName="Helvetica-Oblique")
        ))

    story.append(PageBreak())

    # ── Papers list ───────────────────────────────────────────
    story.append(Paragraph("Papers Compared", heading1))
    story.append(HRFlowable(
        width="100%", thickness=0.5, color=BLUE, spaceAfter=6
    ))
    for i, paper in enumerate(papers):
        meta   = comparison_data["metadata"][i]
        authors = meta.get("authors", ["Unknown"])
        author_str = (
            f"{authors[0]} et al." if len(authors) > 2
            else ", ".join(authors)
        )
        marker = " 🏆" if i == winner_idx else ""
        story.append(Paragraph(
            f"{i+1}. <b>{paper}{marker}</b> "
            f"({author_str}, {meta.get('year','n.d.')})",
            body_style
        ))
    story.append(Spacer(1, 0.2*inch))

    # ── Part A: Score table ───────────────────────────────────
    story.append(Paragraph("Part A — Comparative Scores", heading1))
    story.append(HRFlowable(
        width="100%", thickness=0.5, color=BLUE, spaceAfter=6
    ))
    story.append(Paragraph(
        "Scores are 1–10 per dimension. "
        "Green = strong (8–10), Amber = moderate (6–7), "
        "Red = weak (1–5).",
        body_style
    ))
    story.append(Spacer(1, 0.1*inch))

    dims_to_score = [d for d in DIMENSION_LABELS if d != "overall"]

    short_papers = [
        (p[:22] + "...") if len(p) > 22 else p
        for p in papers
    ]

    table_data = [
        ["Dimension"] + short_papers
    ]

    def _score_color_pdf(sc: int):
        if sc >= 8:
            return colors.HexColor("#D4EDDA")
        elif sc >= 6:
            return colors.HexColor("#FFF3CD")
        return colors.HexColor("#F8D7DA")

    style_cmds = [
        ("BACKGROUND",  (0, 0),  (-1, 0),   BLUE),
        ("TEXTCOLOR",   (0, 0),  (-1, 0),   colors.white),
        ("FONTNAME",    (0, 0),  (-1, 0),   "Helvetica-Bold"),
        ("FONTSIZE",    (0, 0),  (-1, 0),   8),
        ("FONTNAME",    (0, 1),  (0, -1),   "Helvetica-Bold"),
        ("FONTSIZE",    (0, 1),  (-1, -1),  8),
        ("GRID",        (0, 0),  (-1, -1),  0.3,
         colors.HexColor("#CCCCCC")),
        ("VALIGN",      (0, 0),  (-1, -1),  "MIDDLE"),
        ("ALIGN",       (1, 0),  (-1, -1),  "CENTER"),
        ("LEFTPADDING", (0, 0),  (-1, -1),  4),
        ("RIGHTPADDING",(0, 0),  (-1, -1),  4),
        ("TOPPADDING",  (0, 0),  (-1, -1),  4),
        ("BOTTOMPADDING",(0,0),  (-1, -1),  4),
    ]

    for ri, dim in enumerate(dims_to_score):
        dim_sc = scores.get(dim, [5] * len(papers))
        row    = [DIMENSION_LABELS[dim]] + [str(s) for s in dim_sc]
        table_data.append(row)
        for ci, sc in enumerate(dim_sc):
            style_cmds.append((
                "BACKGROUND",
                (ci + 1, ri + 1),
                (ci + 1, ri + 1),
                _score_color_pdf(sc)
            ))

    # Totals row
    tot_row_data = ["TOTAL"] + [
        f"{t} 🏆" if i == winner_idx else str(t)
        for i, t in enumerate(totals)
    ]
    table_data.append(tot_row_data)
    tot_ri = len(dims_to_score) + 1
    style_cmds += [
        ("BACKGROUND", (0, tot_ri), (0, tot_ri), BLUE),
        ("TEXTCOLOR",  (0, tot_ri), (0, tot_ri), colors.white),
        ("FONTNAME",   (0, tot_ri), (-1, tot_ri), "Helvetica-Bold"),
        ("BACKGROUND",
         (winner_idx + 1, tot_ri),
         (winner_idx + 1, tot_ri),
         GREEN),
        ("TEXTCOLOR",
         (winner_idx + 1, tot_ri),
         (winner_idx + 1, tot_ri),
         colors.white),
    ]

    col_w = [1.8*inch] + [
        (5.5 / len(papers)) * inch for _ in papers
    ]
    t = Table(table_data, colWidths=col_w)
    t.setStyle(TableStyle(style_cmds))
    story.append(t)
    story.append(Spacer(1, 0.15*inch))
    story.append(Paragraph(
        f"Winner: <b>{winner}</b>  |  "
        f"Score: {totals[winner_idx]}/{len(dims_to_score)*10}",
        ParagraphStyle("ws", parent=styles["Normal"],
                       fontSize=10, textColor=GREEN,
                       fontName="Helvetica-Bold")
    ))

    story.append(PageBreak())

    # ── Part B: Narratives ────────────────────────────────────
    story.append(Paragraph(
        "Part B — Detailed Narrative Analysis", heading1
    ))
    story.append(HRFlowable(
        width="100%", thickness=0.5, color=BLUE, spaceAfter=6
    ))

    for i, (dim, label) in enumerate(DIMENSION_LABELS.items(), 1):
        story.append(Paragraph(f"{i}. {label}", heading2))
        text = narratives.get(dim, "Analysis not available.")
        for para in text.split("\n\n"):
            if para.strip():
                story.append(Paragraph(
                    para.strip().replace("\n", " "),
                    body_style
                ))
        story.append(Spacer(1, 0.1*inch))

    doc.build(story)
    buf.seek(0)
    return buf.getvalue()


# ── Filename helper ───────────────────────────────────────────────────────────
def generate_comparison_filename(
    papers: list,
    extension: str
) -> str:
    """
    Generates a clean filename from paper titles.
    e.g. ['Paper A', 'Paper B'] → 'comparison_PaperA_vs_PaperB_2026.docx'
    """
    clean_names = []
    for p in papers[:3]:
        clean = "".join(
            c for c in p[:20] if c.isalnum() or c == " "
        ).strip().replace(" ", "_")
        clean_names.append(clean)

    year  = datetime.now().strftime("%Y")
    names = "_vs_".join(clean_names)
    return f"comparison_{names}_{year}.{extension}"