# utils/report_exporter.py
# Exports the generated literature review to .docx and .pdf formats.
# DOCX uses python-docx, PDF uses reportlab.

import os
import io
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()


# ── DOCX Export ───────────────────────────────────────────────────────────────
def export_to_docx(review_data: dict) -> bytes:
    """
    Converts the review dict into a formatted Word document.
    Returns bytes that can be downloaded via Streamlit.

    Structure:
    - Cover page (title, date, paper count)
    - Table of contents (manual)
    - 6 sections with proper headings
    - Comparison table
    - References list
    """
    from docx import Document
    from docx.shared import Pt, Inches, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.style import WD_STYLE_TYPE
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement

    doc = Document()

    # ── Page margins ──────────────────────────────────────────
    section = doc.sections[0]
    section.top_margin    = Inches(1)
    section.bottom_margin = Inches(1)
    section.left_margin   = Inches(1.2)
    section.right_margin  = Inches(1.2)

    # ── Helper functions ──────────────────────────────────────
    def add_heading(text: str, level: int = 1):
        heading = doc.add_heading(text, level=level)
        heading.alignment = WD_ALIGN_PARAGRAPH.LEFT
        run = heading.runs[0] if heading.runs else heading.add_run()
        run.font.color.rgb = RGBColor(0x1F, 0x77, 0xB4)
        return heading

    def add_body_text(text: str):
        para = doc.add_paragraph(text)
        para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        for run in para.runs:
            run.font.size = Pt(11)
            run.font.name = "Calibri"
        return para

    def add_divider():
        para = doc.add_paragraph()
        pPr  = para._p.get_or_add_pPr()
        pBdr = OxmlElement("w:pBdr")
        bottom = OxmlElement("w:bottom")
        bottom.set(qn("w:val"),   "single")
        bottom.set(qn("w:sz"),    "6")
        bottom.set(qn("w:space"), "1")
        bottom.set(qn("w:color"), "1F77B4")
        pBdr.append(bottom)
        pPr.append(pBdr)
        return para

    # ── Cover page ────────────────────────────────────────────
    doc.add_paragraph()
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run  = title_para.add_run("Literature Review")
    title_run.font.size = Pt(28)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(0x1F, 0x77, 0xB4)
    title_run.font.name = "Calibri"

    doc.add_paragraph()
    topic_para = doc.add_paragraph()
    topic_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    topic_run  = topic_para.add_run(review_data.get("topic", "Research Review"))
    topic_run.font.size = Pt(16)
    topic_run.font.bold = True
    topic_run.font.name = "Calibri"

    doc.add_paragraph()
    meta_para = doc.add_paragraph()
    meta_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_str   = datetime.now().strftime("%B %d, %Y")
    paper_count = review_data.get("paper_count", 0)
    meta_run   = meta_para.add_run(
        f"Generated on {date_str}\n"
        f"Based on {paper_count} research papers\n"
        f"Generated by RAG Research Assistant"
    )
    meta_run.font.size  = Pt(11)
    meta_run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)
    meta_run.font.name  = "Calibri"

    doc.add_page_break()

    # ── Papers included ───────────────────────────────────────
    add_heading("Papers Reviewed", level=1)
    papers = review_data.get("papers", [])
    for i, paper in enumerate(papers, 1):
        authors = paper.get("authors", ["Unknown"])
        author_str = (
            f"{authors[0]} et al." if len(authors) > 2
            else ", ".join(authors)
        )
        p = doc.add_paragraph(style="List Number")
        run = p.add_run(
            f"{paper.get('title', 'Unknown')} "
            f"({author_str}, {paper.get('year', 'n.d.')})"
        )
        run.font.size = Pt(10)
        run.font.name = "Calibri"

    add_divider()
    doc.add_paragraph()

    # ── Section 1: Introduction ───────────────────────────────
    add_heading("1. Introduction", level=1)
    add_body_text(review_data.get("introduction", ""))
    doc.add_paragraph()

    # ── Section 2: Related Work ───────────────────────────────
    add_heading("2. Related Work", level=1)
    add_body_text(review_data.get("related_work", ""))
    doc.add_paragraph()

    # ── Section 3: Comparison Table ───────────────────────────
    add_heading("3. Comparative Analysis", level=1)
    add_body_text(
        "The following table provides a structured comparison of the "
        "reviewed papers across key dimensions including methodology, "
        "datasets used, key results, and limitations."
    )
    doc.add_paragraph()

    comparison_data = review_data.get("comparison_data", [])
    if comparison_data:
        headers = [
            "Title", "Authors", "Year",
            "Method", "Dataset", "Key Result", "Limitations"
        ]
        table = doc.add_table(
            rows=1 + len(comparison_data),
            cols=len(headers)
        )
        table.style = "Table Grid"

        # Header row
        header_row = table.rows[0]
        for i, header in enumerate(headers):
            cell = header_row.cells[i]
            cell.text = header
            run = cell.paragraphs[0].runs[0]
            run.font.bold  = True
            run.font.size  = Pt(9)
            run.font.name  = "Calibri"
            run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
            # Blue background for header
            tc   = cell._tc
            tcPr = tc.get_or_add_tcPr()
            shd  = OxmlElement("w:shd")
            shd.set(qn("w:val"),   "clear")
            shd.set(qn("w:color"), "auto")
            shd.set(qn("w:fill"), "1F77B4")
            tcPr.append(shd)

        # Data rows
        col_widths = [
            Inches(1.4), Inches(0.9), Inches(0.4),
            Inches(1.2), Inches(0.9), Inches(1.4), Inches(1.1)
        ]
        for row_idx, row_data in enumerate(comparison_data):
            row = table.rows[row_idx + 1]
            for col_idx, header in enumerate(headers):
                cell     = row.cells[col_idx]
                cell.text = str(row_data.get(header, ""))
                run = cell.paragraphs[0].runs[0]
                run.font.size = Pt(8)
                run.font.name = "Calibri"
                # Alternating row colors
                if row_idx % 2 == 0:
                    tc   = cell._tc
                    tcPr = tc.get_or_add_tcPr()
                    shd  = OxmlElement("w:shd")
                    shd.set(qn("w:val"),   "clear")
                    shd.set(qn("w:color"), "auto")
                    shd.set(qn("w:fill"), "EBF5FB")
                    tcPr.append(shd)

        # Set column widths
        for row in table.rows:
            for col_idx, cell in enumerate(row.cells):
                cell.width = col_widths[col_idx]

    doc.add_paragraph()

    # ── Section 4: Research Gaps ──────────────────────────────
    add_heading("4. Research Gaps", level=1)
    add_body_text(review_data.get("gaps", ""))
    doc.add_paragraph()

    # ── Section 5: Future Directions ─────────────────────────
    add_heading("5. Future Research Directions", level=1)
    add_body_text(review_data.get("future_directions", ""))
    doc.add_paragraph()

    # ── Section 6: Conclusion ─────────────────────────────────
    add_heading("6. Conclusion", level=1)
    add_body_text(review_data.get("conclusion", ""))
    doc.add_paragraph()

    # ── References ────────────────────────────────────────────
    add_divider()
    add_heading("References", level=1)
    for paper in papers:
        authors = paper.get("authors", ["Unknown"])
        if len(authors) > 6:
            author_str = ", ".join(authors[:6]) + " et al."
        else:
            author_str = ", ".join(authors)

        ref_text = (
            f"{author_str} ({paper.get('year', 'n.d.')}). "
            f"{paper.get('title', 'Unknown title')}."
        )
        p    = doc.add_paragraph(style="List Paragraph")
        run  = p.add_run(ref_text)
        run.font.size = Pt(10)
        run.font.name = "Calibri"

    # ── Save to bytes ─────────────────────────────────────────
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()


# ── PDF Export ────────────────────────────────────────────────────────────────
def export_to_pdf(review_data: dict) -> bytes:
    """
    Converts the review dict into a formatted PDF.
    Returns bytes that can be downloaded via Streamlit.
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer,
        Table, TableStyle, PageBreak, HRFlowable
    )
    from reportlab.lib.enums import TA_JUSTIFY, TA_CENTER, TA_LEFT

    buffer = io.BytesIO()
    doc    = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=1.2 * inch,
        leftMargin=1.2 * inch,
        topMargin=1.0 * inch,
        bottomMargin=1.0 * inch
    )

    # ── Styles ────────────────────────────────────────────────
    styles = getSampleStyleSheet()
    BLUE   = colors.HexColor("#1F77B4")
    GRAY   = colors.HexColor("#666666")
    LIGHT  = colors.HexColor("#EBF5FB")

    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=26,
        textColor=BLUE,
        spaceAfter=12,
        alignment=TA_CENTER,
        fontName="Helvetica-Bold"
    )
    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading1"],
        fontSize=14,
        textColor=BLUE,
        spaceBefore=16,
        spaceAfter=8,
        fontName="Helvetica-Bold"
    )
    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["Normal"],
        fontSize=10,
        leading=16,
        spaceAfter=10,
        alignment=TA_JUSTIFY,
        fontName="Helvetica"
    )
    caption_style = ParagraphStyle(
        "Caption",
        parent=styles["Normal"],
        fontSize=9,
        textColor=GRAY,
        alignment=TA_CENTER,
        fontName="Helvetica-Oblique"
    )

    story = []

    # ── Cover page ────────────────────────────────────────────
    story.append(Spacer(1, 1.5 * inch))
    story.append(Paragraph("Literature Review", title_style))
    story.append(Spacer(1, 0.2 * inch))
    story.append(Paragraph(
        review_data.get("topic", "Research Review"),
        ParagraphStyle(
            "TopicStyle",
            parent=styles["Normal"],
            fontSize=14,
            textColor=colors.black,
            alignment=TA_CENTER,
            fontName="Helvetica-Bold",
            spaceAfter=20
        )
    ))
    story.append(Spacer(1, 0.3 * inch))
    date_str = datetime.now().strftime("%B %d, %Y")
    story.append(Paragraph(
        f"Generated: {date_str} &nbsp;|&nbsp; "
        f"Papers reviewed: {review_data.get('paper_count', 0)}",
        ParagraphStyle(
            "MetaStyle",
            parent=styles["Normal"],
            fontSize=10,
            textColor=GRAY,
            alignment=TA_CENTER
        )
    ))
    story.append(PageBreak())

    # ── Papers reviewed list ──────────────────────────────────
    story.append(Paragraph("Papers Reviewed", heading_style))
    story.append(HRFlowable(
        width="100%", thickness=1,
        color=BLUE, spaceAfter=8
    ))
    for i, paper in enumerate(review_data.get("papers", []), 1):
        authors = paper.get("authors", ["Unknown"])
        author_str = (
            f"{authors[0]} et al." if len(authors) > 2
            else ", ".join(authors)
        )
        story.append(Paragraph(
            f"{i}. <b>{paper.get('title', 'Unknown')}</b> "
            f"({author_str}, {paper.get('year', 'n.d.')})",
            body_style
        ))
    story.append(Spacer(1, 0.2 * inch))

    # ── Sections ──────────────────────────────────────────────
    sections = [
        ("1. Introduction",              "introduction"),
        ("2. Related Work",              "related_work"),
        ("4. Research Gaps",             "gaps"),
        ("5. Future Research Directions","future_directions"),
        ("6. Conclusion",                "conclusion"),
    ]

    # Insert comparison table after section 2
    for heading_text, key in sections:
        story.append(Paragraph(heading_text, heading_style))
        story.append(HRFlowable(
            width="100%", thickness=0.5,
            color=BLUE, spaceAfter=6
        ))
        content = review_data.get(key, "")
        for para_text in content.split("\n\n"):
            if para_text.strip():
                story.append(Paragraph(
                    para_text.strip().replace("\n", " "),
                    body_style
                ))
        story.append(Spacer(1, 0.15 * inch))

        # Insert comparison table after related work
        if key == "related_work":
            story.append(Paragraph(
                "3. Comparative Analysis", heading_style
            ))
            story.append(HRFlowable(
                width="100%", thickness=0.5,
                color=BLUE, spaceAfter=6
            ))
            story.append(Paragraph(
                "The table below compares the reviewed papers across "
                "key dimensions.",
                body_style
            ))
            story.append(Spacer(1, 0.1 * inch))

            comparison_data = review_data.get("comparison_data", [])
            if comparison_data:
                headers = [
                    "Title", "Authors", "Year",
                    "Method", "Key Result"
                ]
                table_data = [headers]
                for row in comparison_data:
                    table_data.append([
                        Paragraph(str(row.get("Title", ""))[:50],
                                  ParagraphStyle("cell", fontSize=7,
                                                 fontName="Helvetica")),
                        Paragraph(str(row.get("Authors", ""))[:30],
                                  ParagraphStyle("cell", fontSize=7,
                                                 fontName="Helvetica")),
                        Paragraph(str(row.get("Year", "")),
                                  ParagraphStyle("cell", fontSize=7,
                                                 fontName="Helvetica")),
                        Paragraph(str(row.get("Method", ""))[:60],
                                  ParagraphStyle("cell", fontSize=7,
                                                 fontName="Helvetica")),
                        Paragraph(str(row.get("Key Result", ""))[:80],
                                  ParagraphStyle("cell", fontSize=7,
                                                 fontName="Helvetica")),
                    ])

                col_widths = [
                    1.4*inch, 0.9*inch, 0.4*inch,
                    1.3*inch, 1.5*inch
                ]
                t = Table(table_data, colWidths=col_widths)
                t.setStyle(TableStyle([
                    ("BACKGROUND",  (0,0), (-1,0),  BLUE),
                    ("TEXTCOLOR",   (0,0), (-1,0),  colors.white),
                    ("FONTNAME",    (0,0), (-1,0),  "Helvetica-Bold"),
                    ("FONTSIZE",    (0,0), (-1,0),  8),
                    ("ROWBACKGROUNDS", (0,1), (-1,-1),
                     [colors.white, LIGHT]),
                    ("GRID",        (0,0), (-1,-1),
                     0.3, colors.HexColor("#CCCCCC")),
                    ("VALIGN",      (0,0), (-1,-1),  "TOP"),
                    ("LEFTPADDING", (0,0), (-1,-1),  4),
                    ("RIGHTPADDING",(0,0), (-1,-1),  4),
                    ("TOPPADDING",  (0,0), (-1,-1),  4),
                    ("BOTTOMPADDING",(0,0),(-1,-1),  4),
                ]))
                story.append(t)
                story.append(Spacer(1, 0.15 * inch))

    # ── References ────────────────────────────────────────────
    story.append(HRFlowable(
        width="100%", thickness=1,
        color=BLUE, spaceAfter=8
    ))
    story.append(Paragraph("References", heading_style))
    for paper in review_data.get("papers", []):
        authors = paper.get("authors", ["Unknown"])
        if len(authors) > 6:
            author_str = ", ".join(authors[:6]) + " et al."
        else:
            author_str = ", ".join(authors)

        story.append(Paragraph(
            f"{author_str} ({paper.get('year', 'n.d.')}). "
            f"<i>{paper.get('title', 'Unknown title')}</i>.",
            ParagraphStyle(
                "RefStyle",
                parent=styles["Normal"],
                fontSize=9,
                leading=13,
                spaceAfter=6,
                leftIndent=20,
                firstLineIndent=-20,
                fontName="Helvetica"
            )
        ))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()


# ── Filename generator ────────────────────────────────────────────────────────
def generate_filename(topic: str, extension: str) -> str:
    """
    Generates a clean filename from the review topic.
    e.g. 'NLP, Transformers' → 'literature_review_NLP_Transformers_2026.docx'
    """
    clean = topic.replace(",", "").replace(" ", "_")
    clean = "".join(c for c in clean if c.isalnum() or c == "_")
    clean = clean[:40]
    year  = datetime.now().strftime("%Y")
    return f"literature_review_{clean}_{year}.{extension}"